spring:
  profiles:
    active: sit

#返回信息
message:
  messageMap:
    "000000": "success"
    "000001": "必需参数不能为空!"
    "000002": "搜索产品列表失败!"
    "000003": "未获取到公司有权限的分类!"
    "000004": "获取白膜产品失败!"
    "000005": "请登录!"
    "000006": "平台标识无效!"
    "000007": "未获取到公司信息!"
    "000008": "同步产品信息失败!"
    "000009": "搜索推荐方案列表失败!"

fullsearch:
  version: 1.1.2
  updatelog:
    "1.0.0(20180404)": "1.基线版本发布"

    "1.0.1(20180410)": "1.新增内部用户在PC版搜索时取消产品平台数据过滤
                        2.修复产品替换搜索产品名和产品品牌名字段优先级问题
                        3.修改产品型号分词器最小分词为4个的问题
                        4.修复产品编码权重较低时其他条件超出分值排序的问题
                        5.新增抽屉柜、门地柜小类可被互相搜索
                        6.新增产品以关键字搜本类产品增加最匹配数据排最前规则"

    "1.0.2(20180412)": "1.移除(门框/窗框)小类白膜全铺长度限制
                        2.门小类新增±10白膜全铺长度过滤
                        3.变更产品天花小类搜索逻辑
                        4.变更产品地面大类搜索逻辑新增波打线小类
                        5.移除移动端/通用版产品替换接口天花尺寸/天花布局过滤条件参数"

    "1.0.3(20180420)": "1.修改椅子-原椅子小类被搜索小类为通用椅子小类
                        2.修改灯具-吊灯、吸顶灯、筒灯、射灯小类可相互搜索
                        3.背景墙搜索结果业务优化"

    "1.0.4(20180427)": "1.部分门小类间可相互搜索
                        2.新增茶桌小类可被桌类通用业务搜索"

    "1.0.5(20180510)": "1.新增查询非己产品必须为非保密状态(产品保密限制)
                        2.新增REST方式同步产品数据
                        3.新增产品库权限点功能
                        4.新增自定义请求头Host参数兼容
                        5.新增小程序请求头解析公司数据"

    "1.0.6(20180517)": "1.搜索原镜柜白膜新增全铺长度±5过滤条件
                        2.重构部分元数据内存存储方案为缓存方案
                        3.新增小程序搜索业务为B端逻辑
                        4.产品替换搜索型号字段变更为全匹配"

    "1.0.7(20180524)":  "1.新增pc端蓝标控制产品状态功能
                         2.修改产品型号检索产品规则
                         3.全文检索新增资源文件视图解析器
                         4.搜索引擎新增产品品牌分词器远程扩展词库"

    "1.0.8(20180525)":  "1.三度云享家小程序搜索时去掉品牌/平台限制"

    "1.0.9(20180531)":  "1.B端产品替换新增增天花随机拼花搜索
                         2.新增门框产品全铺长度搜索范围为±10cm
                         3.新增门框产品搜索不到时移除全铺长度条件并取最接近产品全铺长度过滤
                         4.内部用户查看产品不受产品保密(公开)状态限制"

    "1.1.0(20180614)":  "1.增加推荐方案搜索
                         2.更改产品信息品牌字段分词类型
                         3.产品背景墙高度搜索范围更改为0-30-50-260
                         4.产品背景墙长度搜索范围更改为不包含最小值
                         5.修复产品品牌有特殊字符时无法被搜索的问题
                         6.小程序端产品替换搜索新增分类数据聚合
                         7.产品数据新增消息队列实时同步搜索引擎
                         8.推荐方案数据新增消息队列实时同步搜索引擎
                         9.新增橱柜全台面小类搜索"

    "1.1.1(20180621)":  "1.修复小程序产品替换搜索同行排他业务失效"

    "1.1.2(20180630)":  "1.内存方案优化,模块拆分
                         2.小程序产品搜索聚合条件新增小类字段
                         3.推荐方案接口新增点赞数和收藏数字段"
                         
    "1.1.3(20180703)":  "1.一件装修产品搜索走es(未使用)"

    "1.1.4(20180706)":  "1.Fixed the bug WEIXINBUG-345, Added the product release logic check for mini program platform."
    
    "1.1.5(20180710)":  "1.一件装修产品搜索走es,
                         2.本地调试模拟登录信息模式"
    "1.1.6(20180713)":  "1.新需求WEIXIN-121"
    "1.1.7(20180713)":  "1.解决bug"