#Rabbit Mq
spring:
  rabbitmq:
    host: 10.10.30.134
    port: 5672
    username: admin
    password: 123456abc
    publisher-confirms: true
    #virtual-host: test

elasticsearch:
  uri:
    - 10.10.30.81:9200
    - 10.10.30.82:9200
    - 10.10.30.83:9200
    - 10.10.30.84:9200

#Log System
logging:
  config: classpath:log4j2.xml
  level: info