#DateSource
datasource:
  url: jdbc:mysql://db.mysql.sanduspace.com:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
  username: dbuser
  password: Adbuser*$@sandu

#Log System
logging:
  config: classpath:newlog4j2.xml
  level: info

#RPC Servive
dubbo:
  applicationName: sandu-cloud-search-provider
  registryAddress: zookeeper01.sanduspace.cn:2181
  transProtocolName: dubbo
  transProtocolPort: 20666
  providerServicesList:
    - com.sandu.search.service.product.ProductBrandSearchService-productBrandSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductNameSearchService-productNameSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductStyleSearchService-productStyleSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductTextureSearchService-productTextureSearchService-dubbo-3000-1.0.0

#Elasticsearch Service
elasticsearch:
  uri:
    - 10.10.20.81:9200
    - 10.10.20.82:9200
    - 10.10.20.83:9200
    - 10.10.20.84:9200
  indexProductData: false
  initGroupProductIndex: false
  initHouseIndex: false

#Login Redis
redis:
  #格式：redis://:[密码]@[服务器地址]:[端口]/[db index]
  uri: redis://:sanduspace@redislogin.sanduspace.com:33436/0
  pool:
    maxActive: 600
    maxIdle: 600
    minIdle: 10
    maxWaitMillis: 20000
    maxWait: 1000

#Tomcat
server:
  port: 49080
  session:
    timeout: 7200
  tomcat:
    uri-encoding: UTF-8
  context-path: /fullsearch-app

#Rabbit Mq
spring:
  rabbitmq:
    host: amqp.sanduspace.com
    port: 5672
    username: admin
    password: 123456abc
    publisher-confirms: true
    #virtual-host: test