#DateSource
datasource:
  url: jdbc:mysql://192.168.1.107:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
  username: root
  password: Sandu_218root

#Log System
logging:
  config: classpath:newlog4j2.xml
  level: info

#RPC Servive
dubbo:
  applicationName: sandu-cloud-search-provider
  registryAddress: 127.0.0.1:2181
  transProtocolName: dubbo
  transProtocolPort: 20666
  providerServicesList:
    - com.sandu.search.service.product.ProductBrandSearchService-productBrandSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductNameSearchService-productNameSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductStyleSearchService-productStyleSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductTextureSearchService-productTextureSearchService-dubbo-3000-1.0.0

#Server And Https Config
#server:
#  port: 443
#  httpport: 9999
#  session:
#    timeout: 7200
#  tomcat:
#    uri-encoding: UTF-8
#  context-path: /fullsearch-app
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: -Tq8UA7z
#    keyStoreType: PKCS12
#    keyAlias: pxg

#Elasticsearch Service
elasticsearch:
  uri:
    - 192.168.1.101:9200
    - 192.168.1.113:9200
    - 192.168.1.114:9200
    - 192.168.1.207:9200
  indexProductData: false
  initGroupProductIndex: false
  initHouseIndex: false

#Login Redis
#redis:
#  #格式：redis://:[密码]@[服务器地址]:[端口]/[db index]
#  uri: redis://:123456@127.0.0.1:6379/0
#  pool:
#    maxActive: 10
#    maxIdle: 5
#    minIdle: 10
#    maxWaitMillis: 20000
#    maxWait: 300

#Tomcat
server:
  port: 9999
  session:
    timeout: 7200
  tomcat:
    uri-encoding: UTF-8
  context-path: /fullsearch-app
tomcat:
  util:
    http:
      parser:
        HttpParser:
          requestTargetAllow: "|{}"

#Rabbit Mq
spring:
  rabbitmq:
    host: 192.168.1.208
    port: 5672
    username: dev
    password: 8b1asglk
    publisher-confirms: true
    #virtual-host: test