#Host: 10.10.30.97
#Path: /data001/apps/application
#Commond: nohup java -Xms1g -Xmx4g -jar sandu-cloud-search-1.0-SNAPSHOT.jar  --spring.profiles.active=sit --elasticsearch.indexProductData=false --server.port=6666 >sandu-cloud-search.log &
#DB Bak Account: test_luogz/JRMPih27SCGk9s7V
#DateSource
datasource:
  url: jdbc:mysql://db.mysql.ci.sanduspace.com:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
  username: user_dep
  password: ?,iN%er(/8ZEr<*nNX11

#  url: jdbc:mysql://10.10.30.99:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#  username: dev_zhangwj
#  password: abc123

#Log System
logging:
  config: classpath:newlog4j2.xml
  level: info

#RPC Servive
dubbo:
  applicationName: sandu-cloud-search-provider
  registryAddress: zookeeper01.ci.sanduspace.com:2181
  transProtocolName: dubbo
  transProtocolPort: 20666
  providerServicesList:
    - com.sandu.search.service.product.ProductBrandSearchService-productBrandSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductNameSearchService-productNameSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductStyleSearchService-productStyleSearchService-dubbo-3000-1.0.0
    - com.sandu.search.service.product.ProductTextureSearchService-productTextureSearchService-dubbo-3000-1.0.0

#Elasticsearch Service
elasticsearch:
  uri:
    - 10.10.30.81:9200
    - 10.10.30.82:9200
    - 10.10.30.83:9200
    - 10.10.30.84:9200
  indexProductData: true
  initGoodsData: false
  indexGroupProductData: false
  initHouseIndex: false
  indexRecommendationPlanData: false
  reIndexProductDataIndexName : product_info_20180829
  reIndexGoodsDataIndexName : goods_info_20180801
  recommendedPlanDataIndexName: recommendedplan_info_20181129
  reIndexGroupProductDataIndexName : group_product_info

#Redis
redis:
  #格式：redis://:[密码]@[服务器地址]:[端口]/[db index]
  uri: redis://:sanduspace@10.10.30.98:33436/0
  #uri: redis://:sanduspace@redis.ci.sanduspace.com:33434/0
  pool:
    maxActive: 600
    maxIdle: 600
    minIdle: 10
    maxWaitMillis: 20000
    maxWait: 1000
    maxTotal: 6000

#Tomcat
server:
  port: 15000
  session:
    timeout: 7200
  tomcat:
    uri-encoding: UTF-8
    #min-spare-threads: 50
    #max-connections: 200
    #max-threads: 200
  context-path: /fullsearch-app
  #connection-timeout: 5000
tomcat:
  util:
    http:
      parser:
        HttpParser:
          requestTargetAllow: "|{}"

#Rabbit Mq
spring:
  rabbitmq:
    host: amqp.ci.sanduspace.com
#    host: 10.10.30.134
    port: 5672
    username: admin
    password: 123456abc
    publisher-confirms: true
    #virtual-host: test

#Sync task
task:
  product:
    incr:
      cron: 0 0/5 * * * ?
      fullSyncNum: 30
    all: #43200000
      cron: 0 0 0 * * ?
  recommendationplan:
    all:
      cron: 0 0 3 * * ?
    incr:
      cron: 0 0/8 * * * ?
  goods:
    incr:
      cron: 0 0/5 * * * ?
    all:
      cron: 0 0 2 * * ?


#Init meta data
init:
  metadatafinish: false