package com.sandu.api.system.input;

import com.sandu.api.system.model.AuthorizedConfig;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class AuthorizedConfigSearch extends AuthorizedConfig implements Serializable{
private static final long serialVersionUID = 1L;
	/**  序列号-模糊查询  **/
	private String sch_AuthorizedCode_;
	/**  序列号-左模糊查询  **/
	private String sch_AuthorizedCode;
	/**  序列号-右模糊查询  **/
	private String schAuthorizedCode_;
	/**  序列号-区间查询-开始字符串  **/
	private String authorizedCodeStart;
	/**  序列号-区间查询-结束字符串  **/
	private String authorizedCodeEnd;
	/**  密码-模糊查询  **/
	private String sch_Password_;
	/**  密码-左模糊查询  **/
	private String sch_Password;
	/**  密码-右模糊查询  **/
	private String schPassword_;
	/**  密码-区间查询-开始字符串  **/
	private String passwordStart;
	/**  密码-区间查询-结束字符串  **/
	private String passwordEnd;
	/**  企业ID-模糊查询  **/
	private String sch_CompanyId_;
	/**  企业ID-左模糊查询  **/
	private String sch_CompanyId;
	/**  企业ID-右模糊查询  **/
	private String schCompanyId_;
	/**  企业ID-区间查询-开始字符串  **/
	private String companyIdStart;
	/**  企业ID-区间查询-结束字符串  **/
	private String companyIdEnd;
	/**  品牌ID-模糊查询  **/
	private String sch_BrandIds_;
	/**  品牌ID-左模糊查询  **/
	private String sch_BrandIds;
	/**  品牌ID-右模糊查询  **/
	private String schBrandIds_;
	/**  品牌ID-区间查询-开始字符串  **/
	private String brandIdsStart;
	/**  品牌ID-区间查询-结束字符串  **/
	private String brandIdsEnd;
	/**  大分类-模糊查询  **/
	private String sch_BigType_;
	/**  大分类-左模糊查询  **/
	private String sch_BigType;
	/**  大分类-右模糊查询  **/
	private String schBigType_;
	/**  大分类-区间查询-开始字符串  **/
	private String bigTypeStart;
	/**  大分类-区间查询-结束字符串  **/
	private String bigTypeEnd;
	/**  小分类-模糊查询  **/
	private String sch_SmallType_;
	/**  小分类-左模糊查询  **/
	private String sch_SmallType;
	/**  小分类-右模糊查询  **/
	private String schSmallType_;
	/**  小分类-区间查询-开始字符串  **/
	private String smallTypeStart;
	/**  小分类-区间查询-结束字符串  **/
	private String smallTypeEnd;
	/**  小分类ids-模糊查询  **/
	private String sch_SmallTypeIds_;
	/**  小分类ids-左模糊查询  **/
	private String sch_SmallTypeIds;
	/**  小分类ids-右模糊查询  **/
	private String schSmallTypeIds_;
	/**  小分类ids-区间查询-开始字符串  **/
	private String smallTypeIdsStart;
	/**  小分类ids-区间查询-结束字符串  **/
	private String smallTypeIdsEnd;
	/**  产品IDS-模糊查询  **/
	private String sch_ProductIds_;
	/**  产品IDS-左模糊查询  **/
	private String sch_ProductIds;
	/**  产品IDS-右模糊查询  **/
	private String schProductIds_;
	/**  产品IDS-区间查询-开始字符串  **/
	private String productIdsStart;
	/**  产品IDS-区间查询-结束字符串  **/
	private String productIdsEnd;
	/**  终端IMEI-模糊查询  **/
	private String sch_TerminalImei_;
	/**  终端IMEI-左模糊查询  **/
	private String sch_TerminalImei;
	/**  终端IMEI-右模糊查询  **/
	private String schTerminalImei_;
	/**  终端IMEI-区间查询-开始字符串  **/
	private String terminalImeiStart;
	/**  终端IMEI-区间查询-结束字符串  **/
	private String terminalImeiEnd;
	/**  系统编码-模糊查询  **/
	private String sch_SysCode_;
	/**  系统编码-左模糊查询  **/
	private String sch_SysCode;
	/**  系统编码-右模糊查询  **/
	private String schSysCode_;
	/**  系统编码-区间查询-开始字符串  **/
	private String sysCodeStart;
	/**  系统编码-区间查询-结束字符串  **/
	private String sysCodeEnd;
	/**  创建者-模糊查询  **/
	private String sch_Creator_;
	/**  创建者-左模糊查询  **/
	private String sch_Creator;
	/**  创建者-右模糊查询  **/
	private String schCreator_;
	/**  创建者-区间查询-开始字符串  **/
	private String creatorStart;
	/**  创建者-区间查询-结束字符串  **/
	private String creatorEnd;
	/**  创建时间-区间查询-开始时间  **/
	private Date gmtCreateStart;
	/**  创建时间-区间查询-结束时间  **/
	private Date gmtCreateEnd;
	/**  修改人-模糊查询  **/
	private String sch_Modifier_;
	/**  修改人-左模糊查询  **/
	private String sch_Modifier;
	/**  修改人-右模糊查询  **/
	private String schModifier_;
	/**  修改人-区间查询-开始字符串  **/
	private String modifierStart;
	/**  修改人-区间查询-结束字符串  **/
	private String modifierEnd;
	/**  修改时间-区间查询-开始时间  **/
	private Date gmtModifiedStart;
	/**  修改时间-区间查询-结束时间  **/
	private Date gmtModifiedEnd;
	/**  字符备用1-模糊查询  **/
	private String sch_Att1_;
	/**  字符备用1-左模糊查询  **/
	private String sch_Att1;
	/**  字符备用1-右模糊查询  **/
	private String schAtt1_;
	/**  字符备用1-区间查询-开始字符串  **/
	private String att1Start;
	/**  字符备用1-区间查询-结束字符串  **/
	private String att1End;
	/**  字符备用2-模糊查询  **/
	private String sch_Att2_;
	/**  字符备用2-左模糊查询  **/
	private String sch_Att2;
	/**  字符备用2-右模糊查询  **/
	private String schAtt2_;
	/**  字符备用2-区间查询-开始字符串  **/
	private String att2Start;
	/**  字符备用2-区间查询-结束字符串  **/
	private String att2End;
	/**  备注-模糊查询  **/
	private String sch_Remark_;
	/**  备注-左模糊查询  **/
	private String sch_Remark;
	/**  备注-右模糊查询  **/
	private String schRemark_;
	/**  备注-区间查询-开始字符串  **/
	private String remarkStart;
	/**  备注-区间查询-结束字符串  **/
	private String remarkEnd;

}
